sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 4.1
  - 4.2
  - 4.3
  - 5.6
matrix:
    allow_failures:
        - node_js: 4.0
        - node_js: 4.1
        - node_js: 4.2
        - node_js: 4.3
        - node_js: 5.6
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=units
script: "npm run $TEST_SUITE"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
